apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dp
  labels:
    app: backend
    type: backend
spec:
  template:
    metadata:
      name: redis-pod
      labels:
        app: backend-app
        type: backend
    spec:
      containers:
        - name: redis
          image: redis
  selector:
    matchLabels:
      type: backend
  replicas: 2
